### ISSUE TITLE
Can't start App

### ISSUE THREAD

**Issue by itsmefox** [n3utrino/enl-atitude#14]
I can't start the app after i entered my ingame-name. the App always crashes.

Phone: Sony S (LT26i)
Android-Version: 4.0.4

**Comment by n3utrino** [comment]
Do you have a logcat for me? Did you try to uninstall and install again?

**Comment by itsmefox** [comment]
Yes I uninstalled and installed it more than once.

Logcat:
05-14 09:07:58.785: E/AndroidRuntime(16082): FATAL EXCEPTION: main
05-14 09:07:58.785: E/AndroidRuntime(16082): java.lang.RuntimeException: Unable to start service ch.n3utrino.enlatitude.services.UpdateService@41a77da0 with Intent { cmp=ch.n3utrino.enlatitude/.services.UpdateService }: java.lang.NullPointerException
05-14 09:07:58.785: E/AndroidRuntime(16082):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2396)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at android.app.ActivityThread.access$1900(ActivityThread.java:127)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1221)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at android.os.Handler.dispatchMessage(Handler.java:99)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at android.os.Looper.loop(Looper.java:137)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at android.app.ActivityThread.main(ActivityThread.java:4441)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at java.lang.reflect.Method.invokeNative(Native Method)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at java.lang.reflect.Method.invoke(Method.java:511)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at dalvik.system.NativeStart.main(Native Method)
05-14 09:07:58.785: E/AndroidRuntime(16082): Caused by: java.lang.NullPointerException
05-14 09:07:58.785: E/AndroidRuntime(16082):    at ch.n3utrino.enlatitude.services.LocationController.isBetterLocation(LocationController.java:175)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at ch.n3utrino.enlatitude.services.LocationController.determineBetterLocation(LocationController.java:149)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at ch.n3utrino.enlatitude.services.LocationController.<init>(LocationController.java:131)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at ch.n3utrino.enlatitude.services.UpdateService.onStartCommand(UpdateService.java:106)
05-14 09:07:58.785: E/AndroidRuntime(16082):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2379)
05-14 09:07:58.785: E/AndroidRuntime(16082):    ... 10 more

**Comment by n3utrino** [comment]
Seems like there is no lastLocation for gps provider is your gps active?

**Comment by itsmefox** [comment]
My GPS is always active. I need it for ingress ;)

**Comment by n3utrino** [comment]
Hmmm you're right. Need to look at it when I'm back home.

The exception is in the LocationController where it it tries to find the most accurate gps location. Might be a speciality of the sony rom.

**Comment by itsmefox** [comment]
ok, thank you
